### PR TITLE
WIP: feat: typings

### PR DESCRIPTION
**Pull request by daKmoR**
This is a WIP - do NOT merge.

This PR contains a:
- [x] **code refactor**

### Motivation / Use-Case
To prevent errors as a result of type mismatching.
closes: https://github.com/webpack-contrib/karma-webpack/issues/378

### Additional Info
This is an initial proposal - to spark a discussions on howto do the type linting and possible next steps.

PS: not 100% if everything still works as there where some small refactors needed to allow for proper typing.
PPS: Typings are pretty loose so far and I am by no means an export on this so help is definitely wanted :)

to do the linting you need to run
```
npm run lint:types
```

currently, there are no typing errors... but it would be good to do this linting in the ci?

### CODE REVIEW

**Comment by matthieu-foucault** [comment]
Great work! What you need to do now is import the type definitions from karma and webpack, to get rid of those remaining `any`.

For instance, towards the top of `karma-webpack.js`, you can add the following:

```js
/** @typedef {import('karma').ConfigOptions} KarmaConfigOptions  */
```

And then, type `registerExtraWebpackFiles` as follows:

```js
/**
 * @param {KarmaConfigOptions} config
 * @param {KarmaWebpackController} _controller
 */
```

You'll have an error below saying that `config.files` may be `undefined`, so we should check for that.

I agree that type linting should ultimately be done in the CI

**Comment by matthieu-foucault** [comment]
@daKmoR Let me know how I can help. I can type things (just did this on a massive project this year so I'm pretty efficient with this type of task 😄 )
We should synchronize on Gitter though if you want me to push to this branch

**Comment by daKmoR** [comment]
@matthieu-foucault thx :) 
working together sounds great 💪 - feel free to push more commits to the branch 👍

**Comment by rynclark** [comment]
What’s everyone’s thoughts about rewriting it in TypeScript and changing the build process?

**Comment by daKmoR** [comment]
As discussed in #378 a solution where we have type linting but do not need to require full typescript is probably a better situation for open source projects of this type.
1) still gives you typings for IDE and errors
2) easier for contributors

Also, within webpack it is handled the same way.
Some tweet about it: https://twitter.com/TheLarkInn/status/1078340062440509443

So my vote would be for this approach typings + type linting.

**Comment by rynclark** [comment]
Fair enough, was just throwing the idea out there.

**Comment by matthieu-foucault** [comment]
Yes, this is the option I mentioned [here](https://github.com/webpack-contrib/karma-webpack/issues/378#issuecomment-448423310). We can submit updates to this package later, but we don't need to use it ourselves (that's only if you want to type check your karma config).

**Comment by codymikol** [comment]
Hey @daKmoR is this something you are still interested in at this point?

**Comment by daKmoR** [comment]
hey, I'm afraid that's a no... we have moved on from karma and webpack to [@web/test-runner](https://www.npmjs.com/package/@web/test-runner).

closing this PR

**Pull request closed without merging**
